// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Waless.API.Data;

namespace Waless.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180725103146_AddedUserEntity")]
    partial class AddedUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Waless.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<DateTime>("InscriptionDate");

                    b.Property<bool>("Is_Kid");

                    b.Property<string>("Lang");

                    b.Property<string>("LastName");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Picture");

                    b.Property<string>("Picture_Big");

                    b.Property<string>("Picture_Medium");

                    b.Property<string>("Picture_Small");

                    b.Property<string>("Picture_Xl");

                    b.Property<int>("Status");

                    b.Property<string>("Tracklist");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Waless.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
