// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Waless.API.Data;

namespace Waless.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Waless.API.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cover");

                    b.Property<string>("Cover_big");

                    b.Property<string>("Cover_medium");

                    b.Property<string>("Cover_small");

                    b.Property<string>("Cover_xl");

                    b.Property<string>("Id");

                    b.Property<string>("Link");

                    b.Property<string>("Release_date");

                    b.Property<string>("Title");

                    b.Property<string>("Tracklist");

                    b.Property<string>("Type");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Waless.API.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Id");

                    b.Property<string>("link");

                    b.Property<string>("name");

                    b.Property<string>("picture");

                    b.Property<string>("picture_big");

                    b.Property<string>("picture_medium");

                    b.Property<string>("picture_small");

                    b.Property<string>("picture_xl");

                    b.Property<string>("tracklist");

                    b.Property<string>("type");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Waless.API.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreatorId");

                    b.Property<string>("Picture_medium");

                    b.Property<string>("Title");

                    b.HasKey("PlaylistId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Waless.API.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlbumId");

                    b.Property<int>("ArtistId");

                    b.Property<int>("Duration");

                    b.Property<bool>("Explicit_lyrics");

                    b.Property<string>("Id");

                    b.Property<string>("Link");

                    b.Property<int?>("PlaylistId");

                    b.Property<string>("Preview");

                    b.Property<bool>("Readable");

                    b.Property<string>("Release_date");

                    b.Property<string>("Title");

                    b.Property<string>("Title_short");

                    b.Property<string>("Type");

                    b.HasKey("TrackId");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Waless.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("Gender");

                    b.Property<DateTime>("InscriptionDate");

                    b.Property<bool>("Is_Kid");

                    b.Property<string>("Lang");

                    b.Property<string>("LastName");

                    b.Property<string>("Link");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Picture");

                    b.Property<string>("Picture_Big");

                    b.Property<string>("Picture_Medium");

                    b.Property<string>("Picture_Small");

                    b.Property<string>("Picture_Xl");

                    b.Property<int>("Status");

                    b.Property<string>("Tracklist");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Waless.API.Models.Playlist", b =>
                {
                    b.HasOne("Waless.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Waless.API.Models.Track", b =>
                {
                    b.HasOne("Waless.API.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Waless.API.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Waless.API.Models.Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId");
                });
#pragma warning restore 612, 618
        }
    }
}
